using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SoundEnum
{
   PLAYER_STEP,
   ENEMY_STEP,
   HIT_REACTION,
   HIT_REACTION_ARMOR,
   WEAPON_SLASH,
   JUMP_START,
   KICK,
   KICK_REACTION_ENEMY,
   ENEMY_DEATH,
   ITEM_DESTRUCTION,
   ENEMY_GRUNT_1,
   ENEMY_GRUNT_2,
   ENEMY_GRUNT_3,
   COMBO_POINTS_OVER,
   OPEN_HINT,
   COOLDOWN_OVER,
   ACTIVATE_ABILITY,
   BUTTON_CLICK,
   BUTTON_HOVER,
   AMBIENT_DUNGEON,
   AMBIENT_COURTYARD,
   AMBIENT_THRONE_ROOM
}
